name: 🐛 Report a bug
description: File a bug report
title: "[script title] <bug description>"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for reporting a bug! ⛰
        
        Help us replicate the issue by filling in this form. 
  - type: checkboxes
    id: terms
    attributes:
      label: "Please ensure:"
      options:
        - label: "I included in the issue title the script name I'm referring to." 
          required: true
        - label: I performed a search of the [issue tracker](https://github.com/darkred/Userscripts/issues) and in the relevant Greasyfork [feedback page](https://greasyfork.org/en/users/2160-darkred?sort=updated) to avoid opening a duplicate issue.
          required: true
        - label: The bug is caused by the script itself. It doesn't happen if I disable the script, or in a fresh browser profile.
          required: true
  - type: textarea
    id: the-problem
    attributes:
      label: Describe the problem and how to replicate it
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/video/gif showing the issue, if it’s visual
      description: Files can be dropped in this field
  - type: textarea
    id: logs
    attributes:
      label: Console errors, if any
      render: shell
  - type: input
    id: example-url
    attributes:
      label: Example URL
      description: A REAL URL where the bug appears.
      placeholder: https://example.com/page1.htm
    validations:
      required: true
  - type: input
    id: script-manager
    attributes:
      label: Script Manager
      description: What script manager are you using? (Tampermonkey and Violentmonkey are supported - Greasemonkey is NOT supported)
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: Browser(s) used
      description:  What browsers are you seeing the problem on? (old versions such as Waterfox are NOT supported)
    validations:
      required: true
