name: 🆕 Suggest an improvement or new feature
description: ———
labels: enhancement, under discussion
body:
  - type: markdown
    attributes:
      value: |
        - When referring to an existing script of mine, include its name in parenthesis in the title.
        - Before you request from me to write a new script for you, check in https://greasyfork.org/en/scripts and https://openuserjs.org/ : what you ask might be there already.
  - type: textarea
    attributes:
      label: Description
      description: "Try to be as specific as possible, don't make me have to guess what your suggested improvement or feature is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot
      description: You can provide screenshots/mockups to better visualize your idea. Files can be dropped in this field
  - type: input
    attributes:
      label: Example URL
      description: Include a REAL URL where the feature should appear. Paste a link here
      placeholder: https://example.com/index.html
      value: https://
    validations:
      required: true
